### ISSUE TITLE
Upload possible?

### ISSUE THREAD

**Issue by albwe** [obiba/aws.resourcer#1]
Hi,

thanks really much for this package! I found the download via R from a MiniO-Instance very difficult and your package just works. I am just wondering: Is it possible to upload an altered DataFrame (e.g. as csv) to a MiniO-Server with methods from s3.resourcer?

Thanks in advance!

**Comment by ymarcon** [comment]
Thanks. The purpose of the resources is to provide a read-only access to data or computation facilities, for making analysis. You should have a look at the underlying dependency that does the dirty work: [aws.s3](https://cran.r-project.org/web/packages/aws.s3/)
